### PR TITLE
fix: fixed incorrect behavior on Safari when adding new service and r…

### LINKED ISSUE #49: Issues with the NR1 Status Pages app on Safari
The issue is with Safari (Chrome works):

1. Add new service, type anything into the “Service name” field.
image (4)

2. Oops! page comes up on the first character typed.
image (5)

### LINKED ISSUE #64: Unable to add Google Cloud Status Dashboard, AWS Service Health Dashboard
## Description

I'm unable to add https://status.cloud.google.com/ or https://status.aws.amazon.com/ to my New Relic One Status Pages. I was able to add https://www.cloudflarestatus.com/ without issue.

## Steps to Reproduce

1. New Relic One
2. Status Pages
3. Add new service
4. Service name: Google Cloud Status Dashboard
5. Hostname: https://status.cloud.google.com/
6. Provider: Google
7. Add new service

Creates a new box / status page, but it's empty with a spinner.

## Expected Behaviour

Status page is created.

## Relevant Logs / Console output

```
network.js:53 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at e.value (network.js:53)
    at e.<anonymous> (network.js:34)
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.t.<computed> [as next] (runtime.js:97)
    at n (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at e.<anonymous> (asyncToGenerator.js:21)
value @ dd63659f-6f57-42f2-9428-c5ad151c35af--status-pages.js:1
(anonymous) @ dd63659f-6f57-42f2-9428-c5ad151c35af--status-pages.js:1
u @ index.js:1
(anonymous) @ index.js:1
forEach.t.<computed> @ index.js:1
n @ vendors~dd63659f-6f57-42f2-9428-c5ad151c35af--vendors.js:1
s @ vendors~dd63659f-6f57-42f2-9428-c5ad151c35af--vendors.js:1
(anonymous) @ vendors~dd63659f-6f57-42f2-9428-c5ad151c35af--vendors.js:1
(anonymous) @ vendors~dd63659f-6f57-42f2-9428-c5ad151c35af--vendors.js:1
(anonymous) @ dd63659f-6f57-42f2-9428-c5ad151c35af--status-pages.js:1
(anonymous) @ dd63659f-6f57-42f2-9428-c5ad151c35af--status-pages.js:1
u @ index.js:1
(anonymous) @ index.js:1
forEach.t.<computed> @ index.js:1
n @ vendors~dd63659f-6f57-42f2-9428-c5ad151c35af--vendors.js:1
s @ vendors~dd63659f-6f57-42f2-9428-c5ad151c35af--vendors.js:1
(anonymous) @ vendors~dd63659f-6f57-42f2-9428-c5ad151c35af--vendors.js:1
(anonymous) @ vendors~dd63659f-6f57-42f2-9428-c5ad151c35af--vendors.js:1
(anonymous) @ dd63659f-6f57-42f2-9428-c5ad151c35af--status-pages.js:1
commitLifeCycles @ react-dom.development.js:16085
commitAllLifeCycles @ react-dom.development.js:17386
callCallback @ react-dom.development.js:143
invokeGuardedCallbackDev @ react-dom.development.js:193
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:17582
completeRoot @ react-dom.development.js:19036
performWorkOnRoot @ react-dom.development.js:18965
performWork @ react-dom.development.js:18873
performSyncWork @ react-dom.development.js:18847
interactiveUpdates$1 @ react-dom.development.js:19116
interactiveUpdates @ react-dom.development.js:2167
dispatchInteractiveEvent @ react-dom.development.js:4979
Show 2 more frames
status-page.js:257 Uncaught TypeError: Cannot read property 'stopPropagation' of undefined
    at u.value (status-page.js:257)
    at u.value (status-page.js:263)
    at HTMLUnknownElement.callCallback (react-dom.development.js:143)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:193)
    at invokeGuardedCallback (react-dom.development.js:250)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:264)
    at executeDispatch (react-dom.development.js:555)
    at executeDispatchesInOrder (react-dom.development.js:574)
    at executeDispatchesAndRelease (react-dom.development.js:674)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:682)
value @ dd63659f-6f57-42f2-9428-c5ad151c35af--status-pages.js:1
value @ dd63659f-6f57-42f2-9428-c5ad151c35af--status-pages.js:1
callCallback @ react-dom.development.js:143
invokeGuardedCallbackDev @ react-dom.development.js:193
invokeGuardedCallback @ react-dom.development.js:250
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:264
executeDispatch @ react-dom.development.js:555
executeDispatchesInOrder @ react-dom.development.js:574
executeDispatchesAndRelease @ react-dom.development.js:674
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:682
forEachAccumulated @ react-dom.development.js:656
runEventsInBatch @ react-dom.development.js:810
runExtractedEventsInBatch @ react-dom.development.js:818
handleTopLevel @ react-dom.development.js:4923
batchedUpdates$1 @ react-dom.development.js:19056
batchedUpdates @ react-dom.development.js:2148
dispatchEvent @ react-dom.development.js:5002
interactiveUpdates$1 @ react-dom.development.js:19111
interactiveUpdates @ react-dom.development.js:2167
dispatchInteractiveEvent @ react-dom.development.js:4979
react-dom.development.js:283 Uncaught TypeError: Cannot read property 'stopPropagation' of undefined
    at u.value (status-page.js:257)
    at u.value (status-page.js:263)
    at HTMLUnknownElement.callCallback (react-dom.development.js:143)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:193)
    at invokeGuardedCallback (react-dom.development.js:250)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:264)
    at executeDispatch (react-dom.development.js:555)
    at executeDispatchesInOrder (react-dom.development.js:574)
    at executeDispatchesAndRelease (react-dom.development.js:674)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:682)
value @ dd63659f-6f57-42f2-9428-c5ad151c35af--status-pages.js:1
value @ dd63659f-6f57-42f2-9428-c5ad151c35af--status-pages.js:1
callCallback @ react-dom.development.js:143
invokeGuardedCallbackDev @ react-dom.development.js:193
invokeGuardedCallback @ react-dom.development.js:250
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:264
executeDispatch @ react-dom.development.js:555
executeDispatchesInOrder @ react-dom.development.js:574
executeDispatchesAndRelease @ react-dom.development.js:674
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:682
forEachAccumulated @ react-dom.development.js:656
runEventsInBatch @ react-dom.development.js:810
runExtractedEventsInBatch @ react-dom.development.js:818
handleTopLevel @ react-dom.development.js:4923
batchedUpdates$1 @ react-dom.development.js:19056
batchedUpdates @ react-dom.development.js:2148
dispatchEvent @ react-dom.development.js:5002
interactiveUpdates$1 @ react-dom.development.js:19111
interactiveUpdates @ react-dom.development.js:2167
dispatchInteractiveEvent @ react-dom.development.js:4979
```

## Your Environment

* Browser name and version: Chrome Version 83.0.4103.116 (Official Build) (64-bit)

* Operating System and version: Ubuntu Linux 20.04

## Additional context

Both myself and New Relic staff were able to replicate this behavior independently. Since this is open-source, I'm submitting an issue here. Let me know if you have any questions!

### PR DESCRIPTION
**Pull request by madecki**
…efactored part of the code

closes #49 and closes #64

### CODE REVIEW

File: nerdlets/status-page-dashboard/main-page.js [hunk 1]
```diff
@@ -328,6 +311,13 @@ export default class StatusPagesDashboard extends React.PureComponent {
     this.setState({ createTileModalActive: !createTileModalActive });
   };
 
+  updateInputValue = (event, inputName) => {
+    event.persist();
+    this.setState({
+      [inputName]: event.target.value
```
Comment (madecki) [inline nerdlets/status-page-dashboard/main-page.js:317]: I wanted to use event.target.name, however, it's not propagated to the input element by TextField

File: nerdlets/status-page-dashboard/main-page.js [hunk 2]
```diff
@@ -417,58 +407,44 @@ export default class StatusPagesDashboard extends React.PureComponent {
...
+                event.persist();
+                this.setState({
                   newHostProvider: event.target.value
-                }))
-              }
+                });
+              }}
+              value={this.state.newHostProvider}
             >
               <option>Choose a provider</option>
```
Comment (madecki) [inline nerdlets/status-page-dashboard/main-page.js:435]: It should have some kind of default value OR we need to implement fields validation described here:
https://github.com/newrelic/nr1-status-pages/issues/70
